server:
  port: 8080
  address: 0.0.0.0
spring:
  application:
    name: blog
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/iyue-blog?useSSL=false&serverTimezone=UTC
#    username: root
#    password: 123456
    url: jdbc:mysql://172.18.0.1:3306/blog_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&autoReconnect=true
    username: root
    password: Lzy.010904

  # 邮件配置
  mail:
    host: smtp.qq.com  # QQ邮箱的SMTP服务器地址
    port: 587         # SMTP服务器端口号
    username: 1594133583@qq.com  # 发件人邮箱
    password: uxiefpxpykamggbj  # 邮箱授权码（不是邮箱密码）
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8
    debug: true

  redis:
    host: 127.0.0.1
    port: 6379
    # password:
#    cluster:
#      nodes:
#        - redis://127.0.0.1:6379
#        - redis://127.0.0.1:6380
#        - redis://127.0.0.1:6381
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: NON_NULL # JSON处理时忽略非空字段

mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug

aes:
  key: iTgNXRqU80YZ52+iV7Ew2w==

