spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    
  # 邮件配置
  mail:
    host: smtp.qq.com
    port: 587
    username: your-email@qq.com  # 替换为您的QQ邮箱
    password: your-smtp-password # 替换为您的SMTP授权码
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
    default-encoding: UTF-8
    
# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml  # mapper文件路径
  type-aliases-package: com.blog.entity          # 实体类包路径
  configuration:
    map-underscore-to-camel-case: true          # 开启驼峰命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 显示SQL日志
  global-config:
    db-config:
      id-type: auto  # 主键自增
      table-prefix: ""  # 表名前缀
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# 博客系统配置
blog:
  domain: http://localhost:8080  # 替换为您的实际域名 